### PR TITLE
Fix for issue 13: 'Failed false == true assertion'

### LINKED ISSUE #13: Failed false == true assertion
I got an error message `Failed  false == true` assertion in the initialisation step.
Right about here: https://github.com/vector-of-bool/vscode-gitflow/blob/develop/src/flow.ts#L168

I left all options to their defaults

Digging into it, it appeared that the gitflow/branch section wasn't correctly populated:

```
[gitflow "branch"]
        develop = develop
```

Fixing this by adding `master = master` did the trick. My guess is that both entries are trying to be written at the same time.

Developer console output:
```
/path/to/workbench.main.js:29 [Extension Host] [gitflow] Execute C:\Program Files\Git\cmd\git.exe config gitflow.branch.master master
/path/to/workbench.main.js:29 [Extension Host] [gitflow] Execute C:\Program Files\Git\cmd\git.exe config gitflow.branch.develop develop
/path/to/workbench.main.js:29 [Extension Host] [gitflow] Execute C:\Program Files\Git\cmd\git.exe config --get gitflow.branch.master
/path/to/workbench.main.js:29 [Extension Host] [gitflow] Command "C:\Program Files\Git\cmd\git.exe" returned code 0: 
/path/to/workbench.main.js:29 [Extension Host] [gitflow] Command "C:\Program Files\Git\cmd\git.exe" returned code 255: error: could not lock config file .git/config: File exists

/path/to/workbench.main.js:29 [Extension Host] [gitflow] Command "C:\Program Files\Git\cmd\git.exe" returned code 1: 
/path/to/workbench.main.js:29 [Extension Host] [gitflow] Execute C:\Program Files\Git\cmd\git.exe config --get gitflow.branch.develop
/path/to/workbench.main.js:29 [Extension Host] [gitflow] Command "C:\Program Files\Git\cmd\git.exe" returned code 0: 
/path/to/workbench.main.js:28 false == true
```

### PR DESCRIPTION
**Pull request by ghost**
This fix #13 and a cause of #10

### CODE REVIEW

**Comment by zont** [comment]
Need this fix!!!

**Comment by GianiNoyez** [comment]
Yes, please add this. I'm having trouble aswell when setting up my gitflow.

**Comment by vector-of-bool** [comment]
Sorry for the wait! I've been distracted. I'll get this out as soon as I can.

**Comment by GianiNoyez** [comment]
@vector-of-bool Sorry, I didn't want to rush you. 👍

**Pull request merged**
