### PR TITLE
adding support for bugfix branches

### PR DESCRIPTION
**Pull request by baywet**
this addresses issue https://github.com/vector-of-bool/vscode-gitflow/issues/17
bugfix branches behave exactly like feature branches, it's only a categorization aspect.

### CODE REVIEW

**Comment by vector-of-bool** [comment]
Sorry for the delay. I've been really busy with CMake Tools, but I might have time now to take a look. I'm worried there's quite a lot of code duplication between feature/bugfix, so I might refactor them to a common base.

**Comment by baywet** [comment]
@vector-of-bool no issues. The intent duplicating code was to avoid breaking things by not touching what's existing but I can imagine that's going to add a burden for maintainability.
I pushed a few new commits:
- added a tslint.json to disable a few rules
- fixed a few linting issues (everything was showing up in red, and I wanted to rely on static analysis/linting to make sure I wasn't missing anything)
- added package-lock.json
- fixed an error build with the cp API
- refactored the code for the bugfix implementation to avoid code duplication

hopefully that helps and it's now implemented the proper way.
I though about renaming the feature namespace into something more generic but I wanted to get your opinion before that.
Let me know what you think.

**Comment by vector-of-bool** [comment]
Thanks! I'm away from the home dev box ATM, so I can't merge it for a while.

I (unfortunately) don't have a lot of testing in place, and the codebase has been mostly small enough to not warrant it. I assume you've done some manual validation, at least? I can't see any obvious trouble.

**Comment by baywet** [comment]
Yeah I ran the bugfix cycle and feature cycle with the F5 debug experience and it was working properly.

**Comment by baywet** [comment]
@vector-of-bool any time to look at that?

**Comment by vector-of-bool** [comment]
Sorry for the delay. I got wrapped up in my CMake Tools release and going through user issues over there. I'll take a look right now.

**Comment by baywet** [comment]
thanks! when do you think you'll publish the new version?

**Comment by vector-of-bool** [comment]
I'm having some trouble running the debugger on the project, I've also been having some trouble with some failing hardware. I don't think it's anything related to your changes, though.

**Comment by vector-of-bool** [comment]
I've published 1.2.0, which has bugfix support. I also published 1.2.1 because I forgot to add the CHANGELOG notes for 1.2.0. Oops.

**Comment by baywet** [comment]
Haha those things happen all the time when they are not automated.
Thanks for the collaboration on getting that done! And again great extension, I use it all the time!

**Pull request merged**
